### ISSUE TITLE
Bug: Risk for invalid encryption with mongoose v4.4

### ISSUE THREAD

**Issue by burtonjc** [joegoldbeck/mongoose-encryption#36] opened 2016-05-24 15:25 UTC
There is a new feature in mongoose v4.4 where populated references stay populated after saving the document. This introduced a problem though where the mongoose-encryption hook is potentially getting run with populated references when only an `_id` is going to get persisted. That would result in the `_ac` being calculated using populated data when it is actually the depopulated data that gets persisted. The next time you read that document from the DB, you get an authentication failed error, because the `_ac` was calculated using the populated data.

**Comment by joegoldbeck** [comment] 2016-12-05 19:54
@burtonjc Thanks for filing the issue! I created a [test for this in a branch](https://github.com/joegoldbeck/mongoose-encryption/blob/fc025fde3cc65a98f5f5429161e78522ed8f1735/test/encrypt.coffee#L1637), and can't reproduce. Am I understanding the issue correctly? Has the behavior perhaps been fixed in more recent versions?

**Comment by ashkrishan** [comment] 2016-12-06 11:49
I can't reproduce this behaviour on v4.4.19 either. Is there a sample code to try @burtonjc ?

**Comment by joegoldbeck** [comment] 2017-03-18 22:17
Closing due to inactivity

**Closed by joegoldbeck** 2017-03-18 22:17 UTC
