### ISSUE TITLE
per-document keys

### ISSUE THREAD

**Issue by anselms** [joegoldbeck/mongoose-encryption#57] opened 2017-04-23 12:41 UTC
I'd like to use/extend mongoose-encryption to use distinct encryption and authentication keys per document in a collection.
Do I understand the documentation correctly that this is not possible out of the box ("However, you cannot change the following options once you've started using them for a collection: ..")?
If so, I do not yet see the fundamental reason for this -- does it have to do with authentication that refers to something beyond the document?

Would you agree that it should be possible to extend the plugin this way? My understanding is that the "init" and "save" hooks are per document, so it should be possible to use distinct keys[1].
 
[1] 
I found it a bit hard to get the keys into the plugin; my current plan is to instantiate one Mongoose model per document, with this correct respective key passed to it.

**Comment by anselms** [comment] 2017-04-23 18:10
Ok, just found #56 now -- but would still be interested in thoughts and comments on this.

**Comment by joegoldbeck** [comment] 2017-04-24 02:54
Hi @anselms. Thanks for the request. I think the approach you are suggesting won't scale well, and if you'd like to have a key per document, you'll want to fork it and change the api accordingly. (You'll need to pass an encryption / authentication keypair or secret into every `find`, `save` etc...).

One thing to consider is where you intend to store all those keys. I'd assume that each user would be responsible for storing his/her own keys, or that they would otherwise be stored in an entirely separate place from the documents they decrypt, right?

**Comment by joegoldbeck** [comment] 2017-04-24 02:55
(Closing as dupe of #56)

**Closed by joegoldbeck** 2017-04-24 02:55 UTC
Labels: duplicate

**Comment by anselms** [comment] 2017-04-24 06:57
Hi @joegoldbeck,
thanks for the reply! 
Why do you think it won't scale well? Is it because instantiating Mongoose models is expensive? 
You're right about the keys, it is a bit of a hassle to get them into the Mongoose middleware. I store them separately from this database, encrypted with the user's password.

**Comment by joegoldbeck** [comment] 2017-04-25 04:32
Instantiating Mongoose models is probably expensive. Are you intending them to all point to the same collection, or will you be making a new Mongo collection for each document? (The latter definitely won't scale). I think using abstractions for purposes they don't really fit won't "scale" in a very general sense. In addition to performance bottlenecks, I suspect you'll hit tech limitations, surprising bugs, and accumulate layers of tech debt to make it fit..., generally have a bad time and devote more resources maintaining that solution than just designing a plugin to work per-document.

On the other point: If you're planning to storing encryption keys in a separate datastore, also individually encrypted... How are you mediating the encryption of _those_ keys...?

**Comment by anselms** [comment] 2017-04-28 12:23
My plan is  to point all the documents encrypted with different keys to the same collection. 

I do agree with your general argument on scaling. It's an ugly solution. However, I could not come up with a better idea yet: The problem to solve is getting document-specific keys into the Mongoose middleware, specifically, into the 'save' and 'init' hooks. There is no clean way to do this it seems -- any recommendation or hint on this would be greatly appreciated. (I thought about writing the key into the specific Mongoose model _object_, but could not figure out how).   

Good point about storing the keys themselves. I'll encrypt those with a user password and may use a simpler mechanism than described above to store them.
