### ISSUE TITLE
Mod on _id not allowed error in MongoDB 2.4

### ISSUE THREAD

**Issue by viatsyshyn** [joegoldbeck/mongoose-encryption#16] opened 2015-07-08 10:30 UTC
Hey,

First of all, thank you for this mongoose extension. 

I've got troubles with Travis CI build. When unit tests are run I get following error for some of the tests.

When I disable encryption on user model build goes well. My encryption is configured only on model User with following code:

```javascript
User.plugin(encrypt, {
    secret: settings.encryption_secret,
    requireAuthenticationCode: false,
    encryptedFields: ['field1', 'field2', 'field3', 'field4', 'field5']
  });
```

Also I can't reproduce this error on my local env. This happens only on Travis CI. 

May be somebody has or had similar issue

```
Mod on _id not allowed response_time=901, path=/login, page=1, limit=10, body=undefined, , status=302, response_type=text/html; charset=utf-8, type=api_error, message=Mod on _id not allowed, stack=MongoError: Mod on _id not allowed
    at Object.toError (/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:625:22
    at Server.Base._callHandler (/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:478:18
    at MongoReply.parseBody (/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:436:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:439:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

**Comment by deltreey** [comment] 2015-08-11 23:08
I am currently in the process of debugging this error.  Apparently this tracks to an issue with mongodb prior to version 2.4 http://blog.gaku.net/mod-on-_id-not-allowed/ I think it has to do with mongoose's .save function which may use some sort of upsert functionality that is only reliable in more recent bulids of mongodb

**Comment by deltreey** [comment] 2015-08-12 00:15
So I can determine the direct line that causes the error.

It is caused by encrypting a field in a subdocument following this:
https://github.com/joegoldbeck/mongoose-encryption#encrypt-specific-fields-of-sub-docs

explicitly caused by this:
```javascript
ParentSchema.plugin(encrypt, {
  secret: config.secrets.mongoose,
  additionalAuthenticatedFields: ['fields'],
  encryptedFields: []
});
```

not sure adding authentication to the parent schema causes the error, but that is for sure the line of code that's at fault.  There is no issue with any of the following lines:

```javascript
ChildSchema.plugin(encrypt, {
  secret: config.secrets.mongoose,
  encryptedFields: ['value']
});

ParentSchema.plugin(encrypt.encryptedChildren);
```

only the line above them.  It doesn't seem to be necessary anyway, as the child schema is decrypted just fine without it.

**Comment by deltreey** [comment] 2015-08-12 00:48
also, I guess this issue and #16 are related

**Comment by joegoldbeck** [comment] 2015-09-15 02:28
This still an issue with 1.2.0 and the latest version of Mongoose?

**Comment by deltreey** [comment] 2015-09-15 03:32
I'll try it tomorrow night

**Comment by joegoldbeck** [comment] 2015-09-15 14:13
Awesome. Thanks!

**Comment by deltreey** [comment] 2015-09-17 02:06
I am checking my version.  3.8.35 is the latest mongoose within the dependency list that is in the mongoose-encryption package.json  I'm testing with that version now

**Comment by deltreey** [comment] 2015-09-17 02:07
correction, I'm just an idiot.  updating

**Comment by deltreey** [comment] 2015-09-17 02:26
the error did not go away.  As said previously.  I don't know what benefit I get from adding that line that breaks it

**Comment by joegoldbeck** [comment] 2015-09-17 04:19
Thanks for checking!

The benefit of authenticating the field that contains the child documents is that it alerts the plugin (and you) if they have been tampered with. In certain cases, if those documents could be tampered with without causing errors to be thrown when they were retrieved, it could expose them to decryption by an attacker. For example, as follows:

Without that authentication, an attacker with db write access could take the child documents from one document and move them to another one. This would particularly be a problem if the attacker had legitimate credentials to the decrypted version of one of those documents in the app layer (for example, their user document). If that were the case, they could move encrypted child documents inside a document they don't have application access to into a document they do have application access to, and thereby obtain the encrypted version of those child documents in the app layer.

**Comment by deltreey** [comment] 2015-09-17 11:58
My testing was not very good.  Turns out mongoose 4 breaks my app.  I'll
see if I can get a ccce together for better testing

**Comment by thonythony** [comment] 2015-10-05 08:13
Hey, 

I have the same problem when I perform a save operation after a find by id operation.
(I change only fields that are not encrypted)
The callback of save function returned me this error : 
``MongoError: Mod on _id not allowed``

I use theses versions : 
mongoose 4.1.9
mongoose-encryption 1.2.1
mongodb 2.4.14

Someone can help me ? 

Thanks

**Comment by joegoldbeck** [comment] 2016-04-04 23:54
Closing as `wontfix` for now since upgrading MongoDB fixes it. If this becomes a blocking issue for a number of additional users, or if someone has a PR, happy to revisit.

**Closed by joegoldbeck** 2016-04-04 23:54 UTC
Labels: wontfix
